AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda_02

  Sample SAM Template for lambda_02
Parameters:  
  VPCStack:
    Description: Config VPC 
    Type: String
    Default:  'hype-plugin' 

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:

    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      VpcConfig:
        
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub '${VPCStack}:LambdaSG'
        SubnetIds:
          - Fn::ImportValue: 
              !Sub '${VPCStack}:PublicSubnetAZa'   
          - Fn::ImportValue: 
              !Sub '${VPCStack}:PublicSubnetAZb' 
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get


Outputs:
 
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
