version: 0.2

env:
  variables:
    BUCKET_NAME: lambda011

phases:
      
  install:
    commands:
      # - pip install --upgrade awscli aws-sam-cli
      # - pwd
  # pre_build:
  #   commands:
  #     - cd lambda-01
  #     - pwd
      # - git rev-parse --short HEAD
      # - git show --pretty=format:%b --numstat HEAD
      # - git diff-tree --name-only --no-commit-id HEAD
      # - PATH_GIT=$(git diff-tree --name-only --no-commit-id HEAD)
      # - BUCKET_NAME=$PATH_GIT
#      - |
#        then 
#          echo "bucket $BUCKET_NAME already exists"
#        else
#          echo "Create s3 bucket"
#          aws s3 mb s3://$BUCKET_NAME --region  ap-southeast-1
#        fi
  build:
    commands:
  
      # Sam build
      # - echo Package SAM template
      # - echo Package Lambda01..
      #- sam package --template-file lambda-01/template.yaml --output-template-file lambda-01/packaged.yaml --s3-bucket 01lambda
      # - echo Package Lambda02..
      #- sam package --template-file lambda-02/template.yaml --output-template-file lambda-02/packaged.yaml --s3-bucket 02lambda
      - sam package --template-file root_template.yaml --output-template-file root_packaged.yaml --s3-bucket lambdaroot
      # Deploy packaged SAM template
      #- sam deploy --template-file packaged.yaml --stack-name lambda-01-hello-world --region ap-southeast-1
       
cache:
  paths:
    - '/root/.m2/**/*'
    
artifacts:
  type: zip
  files:
    #  - lambda-01/packaged.yaml
    #  - lambda-02/packaged.yaml
     -  root_packaged.yaml