AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Nested application resources
Resources:
   
    rootlambda01:
      Type: AWS::Serverless::Application
      Properties:
        Location: ./lambda-01/template.yaml
       
    rootlambda02:
      Type: AWS::Serverless::Application
      Properties:
        Location: ./lambda-02/template.yaml
     